//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyAwayForSchool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FlyAwayDataEntities : DbContext
    {
        public FlyAwayDataEntities()
            : base("name=FlyAwayDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AeroportOfficiel> AeroportOfficiel { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Vols> Vols { get; set; }
    
        public virtual int InsertOfficielAeroport(string pays, string ville, string aeroport)
        {
            var paysParameter = pays != null ?
                new ObjectParameter("pays", pays) :
                new ObjectParameter("pays", typeof(string));
    
            var villeParameter = ville != null ?
                new ObjectParameter("ville", ville) :
                new ObjectParameter("ville", typeof(string));
    
            var aeroportParameter = aeroport != null ?
                new ObjectParameter("aeroport", aeroport) :
                new ObjectParameter("aeroport", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertOfficielAeroport", paysParameter, villeParameter, aeroportParameter);
        }
    }
}
